import { createSSGHelpers } from "@trpc/react/ssg";
import type { NextPage } from "next";
import Head from "next/head";
import dynamic from 'next/dynamic'
import superjson from "superjson";

import { appRouter, createContext } from "server/router";
import { Footer } from "widgets/footer";

const Header = dynamic<{}>(() =>
  import('widgets/header').then((mod) => mod.Header)
);

export async function getServerSideProps() {
  const ssg = await createSSGHelpers({
    router: appRouter,
    ctx: await createContext(),
    transformer: superjson
  });

  return {
    props: {
      trpcState: ssg.dehydrate(),
    },
  };
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movie-App</title>
        <meta name="description" content="Generated by create-t3-app Movie-App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Footer />
    </>
  );
};

export default Home;
